INSERT INTO brand_type (type) VALUES
('Automotive'),
('Heavy-Duty');

INSERT INTO file_type (name) VALUES ('Brand Image');
INSERT INTO file_type (name) VALUES ('Product Image');


INSERT INTO brand (name, brand_type_id) VALUES
('Acura', 1),
('Pontiac', 1),
('Chrysler / Jeep', 1),
('Infiniti', 1),
('Saab', 1),
('Subaru', 1),
('Honda', 1),
('Suzuki', 1),
('Hyundai', 1),
('Toyota', 1),
('Mercedes-Benz', 1),
('BMW', 1),
('Nissan', 1),
('Renault', 1),
('Volkswagen', 1),
('Ford', 1),
('MG', 1),
('Audi', 1),
('Kia', 1),
('Porsche', 1),
('Land Rover', 1),
('MINI', 1),
('Fiat', 1),
('Jaguar', 1),
('Isuzu', 1),
('Volvo', 1),
('Lexus', 1),
('Chevrolet / GM', 1),
('Datsun', 1),
('Mitsubishi', 1),
('Seat', 1),
('Peugeot', 1),
('Mazda', 1),
('Case', 2),
('John Deere', 2),
('Kenworth', 2),
('Perkins', 2),
('Scania', 2),
('Caterpillar', 2),
('Ford', 2),  -- Nota: Ford aparece dos veces, asegurarse de manejar los contextos de marca
('Freightliner', 2),
('Hino', 2),
('International', 2),
('Mercedes', 2),
('Peterbilt', 2),
('Toyota', 2),
('Volvo', 2),
('Baic', 1);

-- Insertando imágenes en la tabla 'file'
INSERT INTO file (name, mime_type, storage_path, object_id, file_type_id) VALUES
('Acura Logo', 'image/png', '/brands/logos/acura.png', 1, 1),
('Pontiac Logo', 'image/png', '/brands/logos/pontiac.png', 2, 1),
('Chrysler Logo', 'image/jpeg', '/brands/logos/chrysler.jpg', 3, 1),
('Infiniti Logo', 'image/jpeg', '/brands/logos/infiniti.jpg', 4, 1),
('Saab Logo', 'image/jpeg', '/brands/logos/saab.jpg', 5, 1),
('Subaru Logo', 'image/png', '/brands/logos/subaru.png', 6, 1),
('Honda Logo', 'image/png', '/brands/logos/honda.png', 7, 1),
('Suzuki Logo', 'image/jpeg', '/brands/logos/suzuki.jpg', 8, 1),
('Hyundai Logo', 'image/jpeg', '/brands/logos/hyundai.jpg', 9, 1),
('Toyota Logo', 'image/png', '/brands/logos/toyota.png', 10, 1),
('Mercedes-Benz Logo', 'image/jpeg', '/brands/logos/mercedes.jpeg', 11, 1),
('BMW Logo', 'image/png', '/brands/logos/bmw.png', 12, 1),
('Nissan Logo', 'image/jpeg', '/brands/logos/nissan.jpeg', 13, 1),
('Renault Logo', 'image/jpeg', '/brands/logos/renault.jpeg', 14, 1),
('Volkswagen Logo', 'image/png', '/brands/logos/volkswagen.png', 15, 1),
('Ford Logo', 'image/jpeg', '/brands/logos/ford.jpeg', 16, 1),
('MG Logo', 'image/jpeg', '/brands/logos/mg.jpg', 17, 1),
('Audi Logo', 'image/jpeg', '/brands/logos/audi.jpg', 18, 1),
('Kia Logo', 'image/jpeg', '/brands/logos/kia.jpg', 19, 1),
('Porsche Logo', 'image/jpeg', '/brands/logos/porsche.jpg', 20, 1),
('Land Rover Logo', 'image/png', '/brands/logos/land_rover.png', 21, 1),
('MINI Logo', 'image/jpeg', '/brands/logos/mini.jpg', 22, 1),
('Fiat Logo', 'image/jpeg', '/brands/logos/fiat.jpg', 23, 1),
('Jaguar Logo', 'image/jpeg', '/brands/logos/jaguar.jpg', 24, 1),
('Isuzu Logo', 'image/jpeg', '/brands/logos/isuzu.jpg', 25, 1),
('Volvo Logo', 'image/jpeg', '/brands/logos/volvo.jpg', 26, 1),
('Lexus Logo', 'image/jpeg', '/brands/logos/lexus.jpg', 27, 1),
('Chevrolet Logo', 'image/png', '/brands/logos/chevrolet.png', 28, 1),
('Datsun Logo', 'image/png', '/brands/logos/datsun.png', 29, 1),
('Mitsubishi Logo', 'image/jpeg', '/brands/logos/mitsubishi.jpg', 30, 1),
('Seat Logo', 'image/png', '/brands/logos/seat.png', 31, 1),
('Peugeot Logo', 'image/jpeg', '/brands/logos/peugeot.jpg', 32, 1),
('Mazda Logo', 'image/jpeg', '/brands/logos/mazda.jpg', 33, 1),
('Case Logo', 'image/png', '/brands/logos/case.png', 34, 1),
('John Deere Logo', 'image/png', '/brands/logos/john_deere.png', 35, 1),
('Kenworth Logo', 'image/png', '/brands/logos/kenworth.png', 36, 1),
('Perkins Logo', 'image/png', '/brands/logos/perkins.png', 37, 1),
('Scania Logo', 'image/png', '/brands/logos/scania.png', 38, 1),
('Caterpillar Logo', 'image/png', '/brands/logos/caterpillar.png', 39, 1),
('Ford Trucks Logo', 'image/jpeg', '/brands/logos/ford.jpeg', 40, 1),
('Freightliner Logo', 'image/jpeg', '/brands/logos/freightliner.jpg', 41, 1),
('Hino Logo', 'image/png', '/brands/logos/hino.png', 42, 1),
('International Logo', 'image/jpeg', '/brands/logos/international.jpg', 43, 1),
('Mercedes Trucks Logo', 'image/jpeg', '/brands/logos/mercedes.jpeg', 44, 1),
('Peterbilt Logo', 'image/png', '/brands/logos/peterbilt.png', 45, 1),
('Toyota Trucks Logo', 'image/png', '/brands/logos/toyota.png', 46, 1),
('Volvo Trucks Logo', 'image/jpeg', '/brands/logos/volvo.jpg', 47, 1),
('Baic Logo', 'image/jpeg', '/brands/logos/baic.jpg', 48, 1);



INSERT INTO role(description) VALUES
('ADMINISTRADOR'),
('ASISTENTE');