INSERT INTO brand_type (type) VALUES
('Automotive'),
('Heavy-Duty');

INSERT INTO brand (name,image_url,brand_type_id) VALUES
    ('GM', '/brands/logos/gm.png', 1),
    ('Acura', '/brands/logos/acura.png', 1),
    ('Pontiac', 'brands/logos/pontiac.png', 1),
    ('Chrysler', '/brands/logos/chrysler.jpg', 1),
    ('Daewoo', '/brands/logos/daewoo.jpg', 1), 
    ('Infiniti', '/brands/logos/infiniti.jpg', 1),
    ('Saab', '/brands/logos/saab.jpg', 1),
    ('Subaru', '/brands/logos/subaru.png', 1),
    ('Honda','/brands/logos/honda.png',1),
    ('Suzuki','/brands/logos/suzuki.jpg',1),
    ('Hyundai','/brands/logos/hyundai.jpg',1),
    ('Toyota','/brands/logos/toyota.png',1),
    ('Mercedes-Benz','/brands/logos/mercedes.jpeg',1),
    ('BMW','/brands/logos/bmw.png',1),
    ('Nissan','/brands/logos/nissan.jpeg',1),
    ('Renault','/brands/logos/renault.jpeg',1),
    ('Volkswagen','/brands/logos/volkswagen.png',1),
    ('Ford','/brands/logos/ford.jpeg',1),
    ('MG','/brands/logos/mg.jpg',1),
    ('Audi','/brands/logos/audi.jpg',1),
    ('Mahindra','brands/logos/mahindra.jpg',1),
    ('Jeep','/brands/logos/jeep.jpg',1),
    ('Kia','/brands/logos/kia.jpg',1),
    ('Porsche','/brands/logos/porsche.jpg',1),
    ('Land Rover','/brands/logos/land_rover.png',1),
    ('MINI','/brands/logos/mini.jpg',1),
    ('Fiat','/brands/logos/fiat.jpg',1),
    ('Jaguar','/brands/logos/jaguar.jpg',1),
    ('Isuzu','/brands/logos/isuzu.jpg',1),
    ('Volvo','/brands/logos/volvo.jpg',1),
    ('Lexus','/brands/logos/lexus.jpg',1),
    ('Chevrolet','/brands/logos/chevrolet.png',1),
    ('Datsun','/brands/logos/datsun.png',1),
    ('Mitsubishi','/brands/logos/mitsubishi.jpg',1),
    ('Seat','/brands/logos/seat.png',1),
    ('Peugot','/brands/logos/peugeot.jpg',1),
    ('Mazda','/brands/logos/mazda.jpg',1),
    ('Case', '/brands/logos/case.png', 2),
    ('John Deere', '/brands/logos/john_deere.png', 2),
    ('Kenworth', '/brands/logos/kenworth.png', 2),
    ('Perkins', '/brands/logos/perkins.png', 2),
    ('Scania', '/brands/logos/scania.png', 2),
    ('Caterpillar', '/brands/logos/caterpillar.png', 2),
    ('Ford', '/brands/logos/ford.jpeg', 2),
    ('Freightliner', '/brands/logos/freightliner,jpg', 2),
    ('Hino', '/brands/logos/hino.png', 2),
    ('International', '/brands/logos/international.jpg', 2),
    ('Mercedes', '/brands/logos/mercedes.jpeg', 2),
    ('Peterbilt', '/brands/logos/peterbilt.png', 2),
    ('Toyota', '/brands/logos/toyota.png', 2),
    ('Volvo', '/brands/logos/volvo.jpg', 2);


