INSERT INTO brand (brand_name) VALUES 
    ('Honda'),
    ('Maruti Suzuki'),
    ('Hyundai'),
    ('Toyota'),
    ('Mercedes-Benz'),
    ('BMW'),
    ('Skoda'),
    ('Nissan'),
    ('Renault'),
    ('Tata'),
    ('Volkswagen'),
    ('Ford'),
    ('MG'),
    ('Audi'),
    ('Mahindra'),
    ('Jeep'),
    ('Kia'),
    ('Porsche'),
    ('Land Rover'),
    ('MINI'),
    ('Maserati'),
    ('Fiat'),
    ('Jaguar'),
    ('Isuzu'),
    ('Volvo'),
    ('Lexus'),
    ('Ssangyong'),
    ('Chevrolet'),
    ('Rolls-Royce'),
    ('Datsun'),
    ('Lamborghini'),
    ('Mitsubishi'),
    ('Ferrari'),
    ('Seat'),
    ('Peugot'),
    ('Suzuki'),
    ('Mazda');
