name: Despliegue en qa EC2


on:
  push:
    branches:
      - qa # Cambia 'main' por la rama que desees


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout código
        uses: actions/checkout@v4


      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH }}
          port: ${{ secrets.QA_PORT }}
          source: "."
          target: "RefaDiaz"


      - name: Ejecutar comandos remotos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH }}
          port: ${{ secrets.QA_PORT }}
          script: |
            cd RefaDiaz/RefaDiazBackend
            npm install
            pm2 restart API
