name: Despliegue en EC2

on:
  push:
    branches:
      - qa # Cambia 'main' por la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA_ENV

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ec2-3-18-102-88.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/RefaDiaz/RefaDiazBackend"

      - name: Ejecutar comandos remotos
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-18-102-88.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /RefaDiaz/RefaDiazBackend
            npm install
            pm2 restart API
