name: Despliegue en qa EC2

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA_ENV

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.QA_HOST }}
          username: ${{ env.QA_USER }}
          key: ${{ env.QA_SSH }}
          port: ${{ env.QA_PORT }}
          source: "."
          target: "RefaDiaz/RefaDiazBackend"

      - name: Ejecutar comandos remotos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.QA_HOST }}
          username: ${{ env.QA_USER }}
          key: ${{ env.QA_SSH }}
          port: ${{ env.QA_PORT }}
          script: |
            cd RefaDiaz/RefaDiazBackend
            npm install
            pm2 restart API
