name: Despliegue en EC2

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA_ENV

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Transferir archivos y ejecutar comandos remotos
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-18-102-88.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -x  # Habilita la traza de comandos
            scp -r ./* ec2-user@ec2-3-18-102-88.us-east-2.compute.amazonaws.com:/RefaDiaz/RefaDiazBackend
            cd /RefaDiaz/RefaDiazBackend
            npm install
            pm2 restart API
