name: Despliegue en QA EC2

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA_ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files and execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.QA_PORT }}
          script: |
            set -x  # Habilita la traza de comandos
            ssh-keyscan -H ${{ secrets.QA_HOST }} >> ~/.ssh/known_hosts
            scp -r . ${{ secrets.QA_USER }}@${{ secrets.QA_HOST }}:/RefaDiaz/RefaDiazBackend
            cd /RefaDiaz/RefaDiazBackend
            npm install
            pm2 restart API
